### ISSUE TITLE
Player invited to team can't join team

### ISSUE THREAD

**Issue by topher2010** [LatvianModder/FTBLib#38] opened 2016-10-15 01:02 UTC
I invite a fellow player on my server to my team so we can share the perms for claimed chunks, and when he tries to join after i invite him to team, he gets an error that states "<player> is not a member of this Team!".  

Well duh, he's trying to join the team!  lmao.  FTBLib 3.0.0.4   and FTBUtils 3.0.0.3

**Comment by LatvianModder** [comment] 2016-10-15 09:11
Yeah, this was fixed in my Dev version, gonna be released soon

**Closed** 2016-10-16 14:12 UTC
Labels: Bug, High Priority

**Comment by dshadowwolf** [comment] 2016-12-04 07:43
I am seeing this issue with FTBLib 3.1.5 and FTBUtils 3.1.4

Seeing this and looking at the release dates on Curse, I was under the impression that this was fixed.

I have tried with one older version and it did not function either. Will test some more.

**Comment by dshadowwolf** [comment] 2016-12-05 15:47
I am seeing this issue with FTBLib 3.1.5 and FTBUtils 3.1.4

Seeing this and looking at the release dates on Curse, I was under the impression that this was fixed.

I have tried with one older version and it did not function either. What can I do to help solve this problem ?

**Comment by topher2010** [comment] 2016-12-05 15:51
I can confirm this is working since the last update, i apologize for not letting you know my findings sooner.

**Comment by isavegas** [comment] 2016-12-05 16:48
Not working on bleeding edge, commit [fede35e](https://github.com/LatvianModder/FTBLib/tree/fede35ed67af89ac3244801ab81aeede93aa76d2). I've toyed with the source, and found that the issue is in [ForgeTeam.addPlayer(IForgePlayer player)](https://github.com/LatvianModder/FTBLib/blob/fede35ed67af89ac3244801ab81aeede93aa76d2/src/main/java/com/feed_the_beast/ftbl/api_impl/ForgeTeam.java#L253). Specifically in that FTBLibTeamPermissions.CAN_JOIN is false. I can't seem to find a way to set that permission to true, so I propose that you add an option for it into ftbl.json and set it to true by default. I'm willing to submit a PR if you would like.

**Comment by topher2010** [comment] 2016-12-05 16:49
it's been working fine for the couple of servers in my server group that have it, we just have to use the chat commands, the GUI doesn't work at all yet.

**Comment by isavegas** [comment] 2016-12-05 16:51
Odd. Did you have to do any configuration? I just realized that I misunderstood what the value was for, so my previous idea is meaningless, but in any case, I can't get it to work at all.

**Comment by topher2010** [comment] 2016-12-05 16:51
nope, didn't change any configurations at all.  Just updated and it's been working ever since.

**Comment by isavegas** [comment] 2016-12-05 16:58
Okay, did more testing. Inviting a player doesn't give them permission to join.

**Comment by isavegas** [comment] 2016-12-05 16:58
In MY version of the mod. Idk what voodoo magic you've done, @topher2010, but can you let me know what version you're running?

**Comment by topher2010** [comment] 2016-12-05 17:00
FTBLib - 1.10.2-3.1.5
FTBUtilities - 1.10.2-3.1.4

We got it working in an earlier version (don't remember which one) and haven't had any problems with it since then, none of our players has mentioned any other issues at least.

**Comment by isavegas** [comment] 2016-12-05 17:17
Found the issue. A stub implementation of hasPermission that does nothing but an ownership check. I'll submit a clean PR in a few minutes.

**Comment by dshadowwolf** [comment] 2016-12-06 06:29
This issue was using the chat commands, but it does sound like the cause has been found and a fix provided. If there is a release in the next couple of days, that's fine - if not I can compile from source, as I've had to do for a couple mods already.

**Comment by LatvianModder** [comment] 2016-12-06 15:35
Fixed in https://github.com/LatvianModder/FTBLib/commit/7921f98fa7837f126597ceeefbdcb24733531e6e
